package dbtest

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// ensurePackageDatabase creates the per-package test database if missing.
// CREATE DATABASE cannot run in a transaction and has no IF NOT EXISTS —
// duplicate_database (42P04) is treated as success. Cross-process create
// races are serialized with an advisory lock on the maintenance connection
// keyed by a hash of the target database name.
func ensurePackageDatabase(ctx context.Context, baseURL, dbName string) error {
	maintURL, err := maintenanceDatabaseURL(baseURL)
	if err != nil {
		return err
	}
	conn, err := pgx.Connect(ctx, maintURL)
	if err != nil {
		return fmt.Errorf("dbtest: connect maintenance DB: %w", err)
	}
	defer func() { _ = conn.Close(ctx) }()

	lockKey := createAdvisoryLockKey(dbName)
	if _, err := conn.Exec(ctx, `SELECT pg_advisory_lock($1)`, lockKey); err != nil {
		return fmt.Errorf("dbtest: acquire create-database lock: %w", err)
	}
	defer func() {
		_, _ = conn.Exec(ctx, `SELECT pg_advisory_unlock($1)`, lockKey)
	}()

	// dbName is always generated by packageTestDBName (safe charset).
	_, err = conn.Exec(ctx, fmt.Sprintf(`CREATE DATABASE %s`, pgx.Identifier{dbName}.Sanitize()))
	if err == nil {
		return nil
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "42P04" {
		return nil
	}
	return fmt.Errorf("dbtest: CREATE DATABASE %s: %w", dbName, err)
}
